using System;

public partial class _404_Default : System.Web.UI.Page
{
    public string[,] _PAGES = new string[15, 3]
    {
        {"aptx.jpg", "APTX-404: Maybe the page has shrunken to a child", "Pssssssssst, if you are reading this you have probably stumbled over suspicious activities of the black organization. <br /><br /> Don't make any noice, if they find you, they will probably do the same to you as they did to this page. Quickly, <a href=\"/\">get away</a> from here, as long as you still can. <br /><br />You are still here? Alright, go quickly and <a href=\"/Service/Contact\">tell Shinoshi</a> about this. Together you might have a chance. <br /><br />Oh no, there is Rum and Gin and Vodka and Vermouth and Korn and Chi.....aaaaaaah"},
        {"yoda.png", "Occured, a 404 error has... Lost a page I have. How embarrassing...", "The dark side I sense in you. Due to a disturbance in the force I couldn\'t find the page you were looking for. <br /><br />Trust in the force, clear your mind, unlearn what you have learned, and find your missing page you will. Alternatively you could just return to the <a href=\"/\">homepage</a>.<br /><br />If this page exist should, <a href=\"/Service/Contact\">contact the High Council</a> you must. They help you can, I\'m sure.<br /><br />Remember, a Jedi's strength flows from the Force. But beware anger, fear, aggression. The dark side are they. Once you start down the dark path, forever will it dominate your destiny."},
        {"404homer.png", "404 PAGE NOT FOUND: DAMN IT WHERE ARE YOU?!", "Which button am I going to press now. HOW CAN I FIX THIS?! <br /><br />If Mr. Shino finds that out, I am going to loose my job. Huh, what is this \"seeeeeeeeeeelf deeeeeee-struuuuuuc-tioooon\". Can't be wrong. <a href=\"/\">*press*</a><br /><br />Ufff, that was close. If you pressed this button the whole website could have exploded. Quickly, <a href=\"/Service/Contact\">eat a donut</a>, maybe a solution will come to your mind. <br /><br />Hmmmm, strawberry...."},
        {"catswhocode.jpg", "404: But we are already working on it!", "Aaaaaaaaaawwwwwwwwwwwwwwwwww, CATS. SOOOOOOOOOOOOOO CUTEEEEEEEEEEEEE. No seriously, CATS ARE CUTE! <br /><br />Oh, you are already here... *Errhmm* Our highly trained coders are already working on this problem. No need to worry about this. You can return <a href=\"/\">here</a> to the main page.<br /><br />You don't think that cats are cute?! Alright, I guess we need to <a href=\"/Service/Contact\">discuss this matter!</a>"},
        {"deadlink.png", "404: Oh, it looks like you found a Dead Link", "He is still so young. WHYYYY?!<br /><br /> Who is going to save Zelda now?! Oh, maybe <a href=\"/\">you could</a>!<br /><br />Wait, if you did't go to save Zelda, and Link is laying there... Who is goi... *AAAAAAAAAAAAAAH* - Ok, maybe ask a <a href=\"/Service/Contact\">hero for aid</a>. <br /><br />Ooooooooooor, let's just wait for the respawn."},
        {"kaitokidcard.jpg", "A KID CARD: 404?! I thought he just steals jewels?", "I can't believe that Kid stole our page. He would never do that unless something is wrong! <br /><br />Maybe he or the page is in danger, we need to <a href=\"/\">assist him</a> in order to save the day!<br/><br />Okay, probably just some joke, it's an anime after all. Let's just <a href=\"/Service/Contact/\">yell at the lousy programmers</a> who coded this shieet!"},
        {"lookingforthepage.gif", "404, 404, 404, 404, 404, 404", "Okay, aha. I see. Okay...<br /><br />Oh, you still haven't left? Here is the <a href=\"/\">homepage</a>. <br /><br />You were looking for a specfic page? I have no clue where it is, but maybe <a href=\"/Service/Contact\">he can help</a> you.<br /><br />Cyaaa, around mate!"},
        {"miesmuschel.jpg", "Ooooh, holy mussel... Where is our beloved page", "Ooooh, holy mussel... Where is our beloved page? - Yes *?????* <br /><br />Ooooh, holy mussel... Wheeeere is ouuuur beloveeeed pageeee?!. - No. *<a href=\"/\">Arrrrrg, screw this</a>* <br /><br />Ooooh, holy mussel... Where is.... ah, you know what? FUCK YOU. I am just going to <a href=\"/Service/Contact\">contact Shino</a>. He sure will know where it is. <br /><br />Why did I even try this?..."},
        {"movealong.gif", "This is not the page you were looking for... Move along, move along...", "Can I see this page please? - ~This is not the page you are looking for...~ <br /><br />What do you think where we are ?! Star Wars?! Screw you, I will <a href=\"/\">find it myself</a>. <br /><br />Actually I am mediclorian. Jedi stuff like this doesn't work on me. So will you help me <a href=\"/Service/Contact\">finding the page</a> now already? <br /><br />*Jesus... always these roleplayers...*"},
        {"notfound.jpg", "404 NOT FOUND - Are you fu***** kidding me?!", "Alright... Calm down... Calm down... <br /><br />I will just return to the <a href=\"/\">homepage</a> now and try it again. <br /><br />Okay. I'm starting to get mad. Let's <a href=\"/Service/Contact\">yell at Shino</a> a little..."},
        {"oops.jpg", "Ooops, wrong Button...", "Okay. I guess let's try <a href=\"/\">this one</a> then... <br /><br />Still does't work huh? Okay. Let\'s yell at the <a href=\"/Service/Contact\">lousy programmer</a> responsible for this shieet!"},
        {"somethingwentwrong.jpg", "Something went wrong...", "I swear I didn't do this! Really it was... ehm... ehm... <br /><br />*Seeing Shino running by* - *Pointing at him* <br /><br />Right, he was it. I saw it! *<a href=\"/\">making \"a move\"</a>* <br /><br />Nah, nah, nah. You stay here and <a href=\"/Service/Contact\">explain this to me</a>. Veeeeeeeeery slowly, so that even I get it."},
        {"spongebob.jpg", "404: GIVE ME THIS PAGE!", "Ehm sir. You are standing towards the wrong direction. *ooh* <br /><br />GIVE ME THIS PAGE! - private or company deposits?*<a href =\"/\">ehm, private</a>* <br /><br />Do you have any information about this page? Can I have your <a href=\"/Service/Contact\">bank card</a> please? <br /><br />Thank you."},
        {"truth-eye.jpg", "404: Some things can't be brought back to life...", "Even for your beloved page. Not even alchemy can bring back the death... <br /><br />Everything in the world has an equivialent value. Besides life... You can <a href=\"/\">still go back</a>.<br /><br />Everyone will learn this lesson. Either the easy or the hard way. Still we need to <a href=\"/Service/Contact\">talk about it</a>...Even a philosopher's stone has a high price for its power..."},
        {"blizzard.png", "404: Will be up soooooooonish...", "You may want to know what that <a href=\"http://wowwiki.wikia.com/wiki/Soon\">means</a>..."}
    };
    public int _RND = (new Random()).Next(0,15);

    protected void Page_Load(object sender, EventArgs e)
    {
        this.Title = "LegacyPlayers | 404";
    }
}