DELETE FROM am_chars_lifetimerank;
DELETE FROM am_chars_ref_gear_slot;
DELETE FROM am_chars_ref_gear;
DELETE FROM am_chars_ref_guild;
DELETE FROM am_chars_ref_guild;
DELETE FROM am_chars_ref_honor;
DELETE FROM am_chars_ref_misc;
DELETE FROM am_chars_data;
DELETE FROM am_guilds_progresshistory;
DELETE FROM rs_attempts;
DELETE FROM rs_auras;
DELETE FROM rs_bossyells;
DELETE FROM rs_chars_rankings;
DELETE FROM rs_chars_rankings_best;
DELETE FROM rs_damage;
DELETE FROM rs_damage_mitgated;
DELETE FROM rs_deaths;
DELETE FROM rs_dispels;
DELETE FROM rs_guilds_speedkills;
DELETE FROM rs_guilds_speedkills_best;
DELETE FROM rs_healing;
DELETE FROM rs_interrupts;
DELETE FROM rs_loot;
DELETE FROM rs_participants;
DELETE FROM rs_progress;
DELETE FROM rs_threat;
DELETE FROM rs_sa_reference;
DELETE FROM rs_sat_reference;
DELETE FROM rs_sata_reference;
DELETE FROM rs_instance_uploader;
DELETE FROM rs_instances;
DELETE FROM gn_uploader;

ALTER TABLE am_chars_lifetimerank AUTO_INCREMENT = 1;
ALTER TABLE am_chars_ref_gear AUTO_INCREMENT = 1;
ALTER TABLE am_chars_ref_gear_slot AUTO_INCREMENT = 1;
ALTER TABLE am_chars_ref_guild AUTO_INCREMENT = 1;
ALTER TABLE am_chars_ref_honor AUTO_INCREMENT = 1;
ALTER TABLE am_chars_ref_misc AUTO_INCREMENT = 1;
ALTER TABLE am_chars_data AUTO_INCREMENT = 1;
ALTER TABLE am_guilds_progresshistory AUTO_INCREMENT = 1;
ALTER TABLE rs_attempts AUTO_INCREMENT = 1;
ALTER TABLE rs_auras AUTO_INCREMENT = 1;
ALTER TABLE rs_bossyells AUTO_INCREMENT = 1;
ALTER TABLE rs_chars_rankings AUTO_INCREMENT = 1;
ALTER TABLE rs_chars_rankings_best AUTO_INCREMENT = 1;
ALTER TABLE rs_damage AUTO_INCREMENT = 1;
ALTER TABLE rs_damage_mitgated AUTO_INCREMENT = 1;
ALTER TABLE rs_deaths AUTO_INCREMENT = 1;
ALTER TABLE rs_dispels AUTO_INCREMENT = 1;
ALTER TABLE rs_guilds_speedkills AUTO_INCREMENT = 1;
ALTER TABLE rs_guilds_speedkills_best AUTO_INCREMENT = 1;
ALTER TABLE rs_healing AUTO_INCREMENT = 1;
ALTER TABLE rs_interrupts AUTO_INCREMENT = 1;
ALTER TABLE rs_loot AUTO_INCREMENT = 1;
ALTER TABLE rs_participants AUTO_INCREMENT = 1;
ALTER TABLE rs_progress AUTO_INCREMENT = 1;
ALTER TABLE rs_threat AUTO_INCREMENT = 1;
ALTER TABLE rs_sa_reference AUTO_INCREMENT = 1;
ALTER TABLE rs_sat_reference AUTO_INCREMENT = 1;
ALTER TABLE rs_sata_reference AUTO_INCREMENT = 1;
ALTER TABLE rs_instances AUTO_INCREMENT = 1;

ALTER TABLE gn_uploader AUTO_INCREMENT = 1;
